[[project]]
name = "cFlake Engine (2020 - 2023)"
desc = "Custom built Rust game engine, with a custom ECS, render library, and GPU based terrain generation system."
#img = "/nice_cflake_terrain.png"
tags = ["ecs", "rust", "graphics", "game-dev", "game-engine-dev"]
links = [
  { name = "Repository", url = "https://github.com/jedjoud10/cflake-engine" },
  { name = "Demo Video", url = "https://www.youtube.com/watch?v=lbgAekmQiOY&ab_channel=Jed037" },
  { name = "New terrain demo video", url = "https://www.youtube.com/watch?v=r_6kavfRgyE&ab_channel=Jed037" },
]

[[project]]
name = "HypoSharp (csharp OpenTK engine) (2019)"
desc = "First game engine I decided to implement in csharp using OpenTK. Managed to implement a deferred rendering pipeline but then moved to rust"
tags = ["graphics", "game-dev", "game-engine-dev"]
links = [
]

[[project]]
name = "Throw It IMGJ-33 (2024)"
desc = "Fourth rewrite of Throw It. Completely overlauhed gameplay and designs"
tags = ["game-dev", "unity", "csharp", "snow-stuff"]
links = [
]

[[project]]
name = "MyAnimeList show ranking vs # of favourites (finalizing project for MDM4U)"
desc = "Simple rust/python fetcher that reads off of some MAL scraper libraries and writes it to a CSV so I can paste it into google sheets"
tags = ["data-management", "rust", "python"]
links = [
]

[[project]]
name = "OpenTK OpenGL Voxel Renderer"
desc = "Simple voxel raymarcher implemented in csharp and OpenGL. Makes use of sparse virtual textures and temporal depth reprojection to accelerate marching"
tags = ["graphics", "csharp"]
#img = "/voxel_raymarcher.png"
links = [
  { name = "Demo Funny Bug Video", url = "https://www.youtube.com/watch?v=Pn0584Uzk7k&ab_channel=Jed037" },
]

[[project]]
name = "Hypothermia (2023 - to be picked up again)"
desc = "WIP tech game where you survive and innovate in the cold lands of Hel."
tags = ["game-dev", "unity", "csharp", "tech", "survival"]
links = [
  { name = "Devlog Channel", url = "https://www.youtube.com/@pigsteel3342/videos" },
  { name = "Devlog Channel 2", url = "https://www.youtube.com/@jed0378/videos" },
]

[[project]]
name = "Machine learning enabled colored ball sorter (2024)"
desc = "Implemented for one of our TEJ4M projects. Project done with a friend"
tags = ["tech", "rpi", "machine learning", "electronics"]
links = [
]


[[project]]
name = "Tic-tac-toe AI with machine learning image recognition (2024)"
desc = "Implemented for our final performance task in TEJ4M. Project done with a friend. Used a custom neural network and algorithmic TTT bot"
tags = ["tech", "rpi", "machine learning", "electronics"]
links = [
]

[[project]]
name = "Lead programmer/engineer for FTC team 23880 (2023) (Nelson High School)"
desc = "Lead Java programmer and engineer. Also one of the drivers for the Bolton and Scarborough competitions"
tags = ["java", "robotics"]
links = [
  { name = "Code Base Respository", url = "https://github.com/jedjoud10/FTC23880" },
]

[[project]]
name = "Prisoner's Dilemma test in Rust"
desc = "Simple personal testing ground for messing around with strategies in the Prisoner's Dilemma Game"
tags = ["rust"]
links = [
  { name = "Respository", url = "https://github.com/jedjoud10/game-theory-test" },
]

[[project]]
name = "Simple Rust wrapper around mcsrvstat.us API"
desc = ""
tags = ["rust"]
links = [
  { name = "Respository", url = "https://github.com/jedjoud10/mc-server-status" },
]

[[project]]
name = "GPU/CPU Procedural Terrain Generator in Unity (2023 - present)"
desc = "Implemented using compute shaders (only for voxelization) and async GPU readback. Supports Job system + Burst for terrain editing and CPU meshing"
tags = ["game-dev", "unity", "csharp"]
#img = "/unity_terrain_good.png"
links = [
    { name = "Demo Video", url = "https://www.youtube.com/watch?v=D4dvcqclPC4&t=217s&ab_channel=Jed037" },
]

[[project]]
name = "Snow Game Prototype"
desc = "Prototype for a snow game. Kinda like a rewrite of OG Throw It?"
tags = ["game-dev", "ue4", "unity", "snow-stuff"]
links = [
  { name = "UE4 Test Video", url = "https://www.youtube.com/watch?v=9GY12-9wfto&t=3s&ab_channel=Jed037" },
  { name = "Unity Test Video", url = "https://www.youtube.com/watch?v=VOfj5LN8Gw0&ab_channel=Jed037" },
]

[[project]]
name = "GPU/CPU Procedural Terrain Generator in Unity (2019)"
desc = "Implemented using compute shaders (voxelization and meshing) and async GPU readback."
tags = ["game-dev", "unity", "csharp"]
links = [
    { name = "Test Video", url = "https://www.youtube.com/watch?v=LkH9zZbKxUA&ab_channel=Jed037" },
]

[[project]]
name = "PC-Compatible Xbox Steering Wheel (2020)"
desc = "Hacked a cheap Xbox steering wheel to make it PC compatible by using an Arduino Nano and NodeJS to emulate user input"
tags = ["arduino", "electronics"]
links = [
]

[[project]]
name = "Discord Bot (degeneracy)"
desc = "Implemented for discord hackathon, then repurposed as a c.ai wrapper to talk to virtual anime girls through discord"
tags = ["discordjs", "javascript"]
links = [
]

[[project]]
name = "DC Brushed Motor Self-Stabilizing Drone (2022 - present)"
desc = "Built a self-stabiliing drone using an Arduino Nano and MPU9250 for my Culminating Activity for TEJ3M"
tags = ["arduino", "electronics"]
links = [
]

[[project]]
name = "Villagers vs Illagers game in WASM4"
desc = "Simple WASM4 game I made with a friend of mine. Implements 2D grid with entities that move around to their objectives"
tags = ["rust", "wasm4"]
links = [
  { name = "Repository", url = "https://github.com/jedjoud10/villagers-vs-illagers" },
]

[[project]]
name = "Interdimensional struggle (2020)"
desc = "Unity game I made with a friend for a weekend game jam."
tags = ["2D", "unity", "csharp"]
links = [
    { name = "Itch Page", url = "https://jed037.itch.io/interdimensional-struggle" },
]

[[project]]
name = "Throw It (2019)"
desc = "First Unity game me and my friends decided to make in middle school. Initally implemented in UE4, moved to Unity."
tags = ["game-dev", "unity", "snow-stuff", "csharp"]
links = [
]

[[project]]
name = "Electrilized (2017)"
desc = "First game idea that I implemented when I first started out game development. Just a small crafting / factory game. "
tags = ["ue4", "tech"]
links = [
]
