[[project]]
name = "Hypothermia (2023 - present)"
desc = "WIP tech game where you survive and innovate in the cold lands of Hel."
tags = ["game-dev", "unity", "tech", "survival"]
links = [
  { name = "Devlog Channel", url = "https://www.youtube.com/@pigsteel3342/videos" },
  { name = "Devlog Channel 2", url = "https://www.youtube.com/@jed0378/videos" },
]

[[project]]
name = "Lead programmer for FTC team 23880 (2023) (Nelson High School)"
desc = "Lead Java programmer. Also one of the leaders in the Design Team and Building Teams"
tags = ["java", "robotics"]
links = [
  { name = "Code Base Respository", url = "https://github.com/jedjoud10/FTC23880" },
]

[[project]]
name = "Simple Rust wrapper around mcsrvstat.us API"
desc = ""
tags = ["rust"]
links = [
  { name = "Respository", url = "https://github.com/jedjoud10/mc-server-status" },
]

[[project]]
name = "GPU/CPU Procedural Terrain Generator in Unity (2023 - present)"
desc = "Implemented using compute shaders (only for voxelization) and async GPU readback. Supports Job system + Burst for terrain editing and CPU meshing"
tags = ["game-dev", "unity"]
links = [
    { name = "Demo Video", url = "https://www.youtube.com/watch?v=D4dvcqclPC4&t=217s&ab_channel=Jed037" },
]

[[project]]
name = "cFlake Engine (2020 - 2023)"
desc = "Custom built Rust game engine, with a custom ECS, render library, and GPU based terrain generation system."
tags = ["ecs", "rust", "graphics", "game-dev", "game-engine-dev"]
links = [
  { name = "Repository", url = "https://github.com/jedjoud10/cflake-engine" },
  { name = "Demo Video", url = "https://www.youtube.com/watch?v=lbgAekmQiOY&ab_channel=Jed037" },
  { name = "New terrain demo video", url = "https://www.youtube.com/watch?v=r_6kavfRgyE&ab_channel=Jed037" },
]

[[project]]
name = "Snow Game Prototype"
desc = "Prototype for a snow game. Initally implemented in UE4, moved to Unity."
tags = ["game-dev", "ue4", "unity"]
links = [
  { name = "UE4 Test Video", url = "https://www.youtube.com/watch?v=9GY12-9wfto&t=3s&ab_channel=Jed037" },
  { name = "Unity Test Video", url = "https://www.youtube.com/watch?v=VOfj5LN8Gw0&ab_channel=Jed037" },
]

[[project]]
name = "GPU/CPU Procedural Terrain Generator in Unity (2019)"
desc = "Implemented using compute shaders (voxelization and meshing) and async GPU readback."
tags = ["game-dev", "unity"]
links = [
    { name = "Test Video", url = "https://www.youtube.com/watch?v=LkH9zZbKxUA&ab_channel=Jed037" },
]

[[project]]
name = "PC-Compatible Xbox Steering Wheel (2020)"
desc = "Hacked a cheap Xbox steering wheel to make it PC compatible by using an Arduino Nano and NodeJS to emulate user input"
tags = ["arduino"]
links = [
]

[[project]]
name = "DC Brushed Motor Self-Stabilizing Drone (2022 - present)"
desc = "Built a self-stabiliing drone using an Arduino Nano and MPU9250 for my Culminating Activity for TEJ3M"
tags = ["arduino"]
links = [
]

[[project]]
name = "Villagers vs Illagers game in WASM4"
desc = "Simple WASM4 game I made with a friend of mine. Implements 2D grid with entities that move around to their objectives"
tags = ["rust", "wasm4"]
links = [
  { name = "Repository", url = "https://github.com/jedjoud10/villagers-vs-illagers" },
]

[[project]]
name = "Interdimensional struggle (2020)"
desc = "Unity game I made with a friend for a weekend game jam. Forgot the name lol."
tags = ["2D", "unity"]
links = [
    { name = "Itch Page", url = "https://jed037.itch.io/interdimensional-struggle" },
]
