[[skill]]
name = "Rust (2020)"
[[skill]]
name = "C# (2019)"
[[skill]]
name = "Unity (2019)"
[[skill]]
name = "Unreal Engine 4 (2019)"
[[skill]]
name = "Python (2020)"
[[skill]]
name = "PyTorch & TensorFlow (2024)"
[[skill]]
name = "Wgpu (2021)"
[[skill]]
name = "Vulkan (2021)"
[[skill]]
name = "OpenGL (2021)"
[[skill]]
name = "Rapier (2021)"
[[skill]]
name = "Linux (2022)"
[[skill]]
name = "Blender (2019)"
[[skill]]
name = "CAD (2023)"
[[skill]]
name = "3D Printing (2023)"
[[skill]]
name = "Soldering (2021)"
[[skill]]
name = "Circuits Design (2022)"
[[skill]]
name = "Arduino & Micro-controllers (2019)"
[[skill]]
name = "Raspberry Pi (2023)"
