[[project]]
name = "Rust"
desc = ""
tags = []
links = []

[[project]]
name = "C#"
desc = ""
tags = []
links = []

[[project]]
name = "Unity"
desc = ""
tags = []
links = []

[[project]]
name = "Unreal Engine 4"
desc = ""
tags = []
links = []

[[project]]
name = "Python"
desc = ""
tags = []
links = []

[[project]]
name = "PyTorch & TensorFlow"
desc = ""
tags = []
links = []

[[project]]
name = "Wgpu"
desc = ""
tags = []
links = []

[[project]]
name = "Vulkan"
desc = ""
tags = []
links = []

[[project]]
name = "OpenGL"
desc = ""
tags = []
links = []

[[project]]
name = "Rapier"
desc = ""
tags = []
links = []

[[project]]
name = "Linux"
desc = ""
tags = []
links = []

[[project]]
name = "Blender"
desc = ""
tags = []
links = []

[[project]]
name = "CAD"
desc = ""
tags = []
links = []

[[project]]
name = "3D Printing"
desc = ""
tags = []
links = []

[[project]]
name = "Soldering"
desc = ""
tags = []
links = []

[[project]]
name = "Circuits Design"
desc = ""
tags = []
links = []

[[project]]
name = "Arduino & Micro-controllers"
desc = ""
tags = []
links = []

[[project]]
name = "Raspberry Pi"
desc = ""
tags = []
links = []